// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4H597p54xPzbv7xXCXIpoN2H5DuvkqI',
    appId: '1:82149486118:ios:8b8dc1dc3a73462d2780e7',
    messagingSenderId: '82149486118',
    projectId: 'trackbud-a5d20',
    storageBucket: 'trackbud-a5d20.appspot.com',
    iosBundleId: 'com.example.trackBud',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwNpwhY1UcNu_0raoOn0k1i7hKH2m8eSc',
    appId: '1:82149486118:android:fb150e9d6032a84b2780e7',
    messagingSenderId: '82149486118',
    projectId: 'trackbud-a5d20',
    storageBucket: 'trackbud-a5d20.appspot.com',
  );

}