name: track_bud
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.3.0
  flutter_svg: ^2.0.10+1
  simple_shadow: ^0.3.1
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.3+1
  fl_chart: ^0.68.0
  dropdown_button2: ^2.3.9
  connectivity_plus: ^6.0.5
  uuid: ^4.4.2
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  firebase_dynamic_links: ^6.0.4
  share: ^2.0.4
  percent_indicator: ^4.2.3
  gap: ^3.0.1

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#3B42E8"
  adaptive_icon_foreground: "assets/icons/android_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/icons/
    - assets/categories/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/Outfit-Regular.ttf
          weight: 400
        - asset: assets/font/Outfit-Medium.ttf
          weight: 500
        - asset: assets/font/Outfit-SemiBold.ttf
          weight: 600
