name: track_bud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  flutter_svg: ^2.0.10+1
  simple_shadow: ^0.3.1
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  modal_bottom_sheet: ^3.0.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/icons/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/Outfit-Regular.ttf
          weight: 400
        - asset: assets/font/Outfit-Medium.ttf
          weight: 500
        - asset: assets/font/Outfit-SemiBold.ttf
          weight: 600
